from typing import Any, Callable, ParamSpec, TypeVar

P = ParamSpec("P")
R = TypeVar("R")

class HTTPException(Exception):
    status_code: int
    detail: Any
    def __init__(self, status_code: int, detail: Any) -> None: ...

class FastAPI:
    def __init__(self, **kwargs: Any) -> None: ...
    def add_middleware(self, middleware_class: type[Any], **kwargs: Any) -> None: ...
    def get(self, path: str, **kwargs: Any) -> Callable[[Callable[P, R]], Callable[P, R]]: ...
    def post(self, path: str, **kwargs: Any) -> Callable[[Callable[P, R]], Callable[P, R]]: ...


def __getattr__(name: str) -> Any: ...
