from typing import Any

class Optimizer:
    param_groups: list[dict[str, Any]]
    def __init__(self, params: Any, defaults: dict[str, Any]) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> dict[str, Any]: ...
    def load_state_dict(self, state_dict: dict[str, Any]) -> None: ...

class AdamW(Optimizer):
    def __init__(
        self,
        params: Any,
        lr: float = ...,
        betas: tuple[float, float] = ...,
        eps: float = ...,
        weight_decay: float = ...,
    ) -> None: ...


def __getattr__(name: str) -> Any: ...
