from typing import Any, Callable
from torch.optim import Optimizer

class LambdaLR:
    def __init__(self, optimizer: Optimizer, lr_lambda: Callable[[int], float]) -> None: ...
    def step(self) -> None: ...
    def get_last_lr(self) -> list[float]: ...
    def state_dict(self) -> dict[str, Any]: ...
    def load_state_dict(self, state_dict: dict[str, Any]) -> None: ...
