from typing import Any, Iterable, Iterator
from torch import Tensor

class Module:
    training: bool
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...
    def to(self, device: str | None = ..., dtype: Any = ...) -> Module: ...
    def eval(self) -> Module: ...
    def train(self, mode: bool = ...) -> Module: ...
    def modules(self) -> Iterator[Module]: ...
    def parameters(self) -> Iterable[Tensor]: ...
    def named_parameters(self) -> Iterable[tuple[str, Tensor]]: ...
    def state_dict(self) -> dict[str, Any]: ...
    def load_state_dict(self, state_dict: dict[str, Any], strict: bool = ...) -> Any: ...
    def register_buffer(self, name: str, tensor: Tensor, persistent: bool = ...) -> None: ...
    def apply(self, fn: Any) -> Module: ...
    def generate(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def __getattr__(self, name: str) -> Any: ...

class Linear(Module):
    weight: Tensor
    bias: Tensor | None
    def __init__(self, in_features: int, out_features: int, bias: bool = ...) -> None: ...

class Embedding(Module):
    weight: Tensor
    def __init__(self, num_embeddings: int, embedding_dim: int) -> None: ...

class LayerNorm(Module):
    def __init__(self, normalized_shape: int, eps: float = ..., bias: bool = ...) -> None: ...

class Dropout(Module):
    p: float
    def __init__(self, p: float = ...) -> None: ...

class GELU(Module):
    def __init__(self, approximate: str = ...) -> None: ...

class ModuleList(Module):
    def __init__(self, modules: Iterable[Module] = ...) -> None: ...
    def __iter__(self) -> Iterator[Module]: ...

class Parameter(Tensor):
    requires_grad: bool

class _Utils:
    def clip_grad_norm_(self, parameters: Iterable[Tensor], max_norm: float) -> Tensor: ...

utils: _Utils

def __getattr__(name: str) -> Any: ...
