from typing import Any
from torch import Tensor

def cross_entropy(input: Tensor, target: Tensor, ignore_index: int = ...) -> Tensor: ...
def log_softmax(input: Tensor, dim: int = ...) -> Tensor: ...
def scaled_dot_product_attention(
    query: Tensor,
    key: Tensor,
    value: Tensor,
    attn_mask: Tensor | None = ...,
    dropout_p: float = ...,
    is_causal: bool = ...,
    scale: float | None = ...,
) -> Tensor: ...
def silu(input: Tensor) -> Tensor: ...
def softmax(input: Tensor, dim: int = ...) -> Tensor: ...
def __getattr__(name: str) -> Any: ...
