from typing import Any, Generic, Iterable, Iterator, Mapping, TypeVar, overload

T = TypeVar("T")

class _Progress(Generic[T]):
    def __iter__(self) -> Iterator[T]: ...
    def set_postfix(self, values: Mapping[str, object]) -> None: ...
    def update(self, n: int = ...) -> None: ...
    def close(self) -> None: ...

class _TqdmFactory:
    @overload
    def __call__(self, iterable: Iterable[T], desc: str | None = ..., leave: bool = ..., total: int | None = ..., unit: str | None = ..., initial: int = ...) -> _Progress[T]: ...
    @overload
    def __call__(self, iterable: None = ..., desc: str | None = ..., leave: bool = ..., total: int | None = ..., unit: str | None = ..., initial: int = ...) -> _Progress[Any]: ...
    def write(self, s: str) -> None: ...

tqdm: _TqdmFactory
