from typing import Any, Callable, ParamSpec, TypeVar, overload

P = ParamSpec("P")
T = TypeVar("T")

class dtype: ...

float32: dtype
float16: dtype
bfloat16: dtype

class Tensor:
    shape: tuple[int, ...]
    ndim: int
    requires_grad: bool
    def to(self, device: str | None = ..., dtype: dtype | None = ...) -> Tensor: ...
    def numel(self) -> int: ...
    def item(self) -> float: ...
    def long(self) -> Tensor: ...
    def copy(self) -> Tensor: ...
    def clone(self) -> Tensor: ...
    def float(self) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def squeeze(self, dim: int | None = ...) -> Tensor: ...
    def mean(self) -> Tensor: ...
    def tolist(self) -> list[int]: ...
    @overload
    def size(self) -> tuple[int, ...]: ...
    @overload
    def size(self, dim: int) -> int: ...
    def view(self, *shape: int) -> Tensor: ...
    def reshape(self, *shape: int) -> Tensor: ...
    def flatten(self, start_dim: int = ..., end_dim: int = ...) -> Tensor: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def repeat_interleave(self, repeats: int, dim: int = ...) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def type_as(self, other: Tensor) -> Tensor: ...
    def scatter_(self, dim: int, index: Tensor, src: Tensor) -> Tensor: ...
    def gather(self, dim: int, index: Tensor) -> Tensor: ...
    def __getitem__(self, key: Any) -> Tensor: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __truediv__(self, other: Any) -> Tensor: ...
    def __mul__(self, other: Any) -> Tensor: ...
    def __add__(self, other: Any) -> Tensor: ...
    def __sub__(self, other: Any) -> Tensor: ...
    def __rtruediv__(self, other: Any) -> Tensor: ...
    def __gt__(self, other: Any) -> Tensor: ...
    def __lt__(self, other: Any) -> Tensor: ...
    def __len__(self) -> int: ...
    def __rpow__(self, other: Any) -> Tensor: ...
    def __radd__(self, other: Any) -> Tensor: ...

class _NoGrad:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> bool | None: ...

def no_grad() -> _NoGrad: ...

class _DeviceProps:
    total_memory: int
    name: str
    major: int
    minor: int

class _CudaModule:
    def is_available(self) -> bool: ...
    def get_device_properties(self, idx: int) -> _DeviceProps: ...
    def current_device(self) -> int: ...

cuda: _CudaModule

class _MPSModule:
    def is_available(self) -> bool: ...

class _BackendsModule:
    mps: _MPSModule

backends: _BackendsModule

def tensor(data: Any, device: str | None = ..., dtype: dtype | None = ...) -> Tensor: ...
def randint(low: int, high: int, size: tuple[int, ...], device: str | None = ...) -> Tensor: ...
def from_numpy(arr: Any) -> Tensor: ...
def arange(
    start: int,
    end: int | None = ...,
    step: int = ...,
    dtype: dtype | None = ...,
    device: str | None = ...,
) -> Tensor: ...
def outer(input: Tensor, vec2: Tensor) -> Tensor: ...
def polar(abs: Tensor, angle: Tensor) -> Tensor: ...
def ones_like(input: Tensor) -> Tensor: ...
def zeros_like(input: Tensor) -> Tensor: ...
def any(input: Tensor) -> bool: ...
def view_as_complex(input: Tensor) -> Tensor: ...
def view_as_real(input: Tensor) -> Tensor: ...
def topk(input: Tensor, k: int, dim: int = ..., largest: bool = ..., sorted: bool = ...) -> tuple[Tensor, Tensor]: ...
def sort(input: Tensor, dim: int = ..., descending: bool = ...) -> tuple[Tensor, Tensor]: ...
def cumsum(input: Tensor, dim: int) -> Tensor: ...
def multinomial(input: Tensor, num_samples: int, replacement: bool = ...) -> Tensor: ...
def cat(tensors: list[Tensor], dim: int = ...) -> Tensor: ...
def save(obj: Any, f: Any) -> None: ...
def load(f: Any, map_location: Any = ..., weights_only: bool = ...) -> Any: ...
def get_num_threads() -> int: ...

@overload
def inference_mode(func: Callable[P, T]) -> Callable[P, T]: ...
@overload
def inference_mode(*, mode: bool = ...) -> Callable[[Callable[P, T]], Callable[P, T]]: ...

def __getattr__(name: str) -> Any: ...
